name: Docker Meta V2

on:
  push:
    branches:
      - development
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Docker meta
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: registry.morenoamor.com/sample-image
          tags: |
            type=ref,event=branch
          flavor: |
            latest=${{ github.ref == 'refs/heads/master' }}
