name: Docker Meta V2

on:
  push:
    branches:
      - development
      - master

jobs:

  meta1:
    name: Docker meta 1
    runs-on: ubuntu-latest
    steps:
      -
        name: Docker meta
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: registry.morenoamor.com/sample-image
          tags: |
            type=schedule
            type=ref,event=branch
            type=edge
            type=ref,event=tag
            type=ref,event=pr
            type=raw,value=personalizada
          flavor: |
            latest=${{ github.ref == 'refs/heads/master' }}

  meta2:
    name: Docker meta 2
    needs: meta1
    runs-on: ubuntu-latest
    steps:
      -
        name: Docker meta
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: registry.morenoamor.com/sample-image2
          tags: |
            type=raw,value=personalizada
          flavor: |
            latest=${{ github.ref == 'refs/heads/master' }}

  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Builder instance name
        run: echo ${{ steps.buildx.outputs.name }}
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

  buildx-quemu:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
