name: Test Python

on:
  push:
    branches: [ master ]

jobs:
  test_python:
    name: Test python action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run python container
      id: run_python_container
      uses: jmorenoamor/test-github-python-action@master

    - name: Run a multi-line script
      run: |
        echo "::set-output name=action_fruit::strawberry"
        echo "::warning file=app.js,line=1,col=5::Missing semicolon"
        echo "::debug file=app.js,line=1::Entered octocatAddition method"
        echo "::error file=app.js,line=10,col=15::Something went wrong"
